// Copyright 2015 Google Inc. All rights reserved.
// GTFS-realtime specification: https://gtfs.org/realtime/proto/
// Licensed under the Apache License, Version 2.0.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: gtfs-realtime.proto

package gtfsrt

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FeedHeader_Incrementality int32

const (
	FeedHeader_FULL_DATASET FeedHeader_Incrementality = 0
	FeedHeader_DIFFERENTIAL FeedHeader_Incrementality = 1
)

// Enum value maps for FeedHeader_Incrementality.
var (
	FeedHeader_Incrementality_name = map[int32]string{
		0: "FULL_DATASET",
		1: "DIFFERENTIAL",
	}
	FeedHeader_Incrementality_value = map[string]int32{
		"FULL_DATASET": 0,
		"DIFFERENTIAL": 1,
	}
)

func (x FeedHeader_Incrementality) Enum() *FeedHeader_Incrementality {
	p := new(FeedHeader_Incrementality)
	*p = x
	return p
}

func (x FeedHeader_Incrementality) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FeedHeader_Incrementality) Descriptor() protoreflect.EnumDescriptor {
	return file_gtfs_realtime_proto_enumTypes[0].Descriptor()
}

func (FeedHeader_Incrementality) Type() protoreflect.EnumType {
	return &file_gtfs_realtime_proto_enumTypes[0]
}

func (x FeedHeader_Incrementality) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *FeedHeader_Incrementality) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = FeedHeader_Incrementality(num)
	return nil
}

// Deprecated: Use FeedHeader_Incrementality.Descriptor instead.
func (FeedHeader_Incrementality) EnumDescriptor() ([]byte, []int) {
	return file_gtfs_realtime_proto_rawDescGZIP(), []int{1, 0}
}

type TripUpdate_StopTimeUpdate_ScheduleRelationship int32

const (
	TripUpdate_StopTimeUpdate_SCHEDULED TripUpdate_StopTimeUpdate_ScheduleRelationship = 0
	TripUpdate_StopTimeUpdate_SKIPPED   TripUpdate_StopTimeUpdate_ScheduleRelationship = 1
	TripUpdate_StopTimeUpdate_NO_DATA   TripUpdate_StopTimeUpdate_ScheduleRelationship = 2
)

// Enum value maps for TripUpdate_StopTimeUpdate_ScheduleRelationship.
var (
	TripUpdate_StopTimeUpdate_ScheduleRelationship_name = map[int32]string{
		0: "SCHEDULED",
		1: "SKIPPED",
		2: "NO_DATA",
	}
	TripUpdate_StopTimeUpdate_ScheduleRelationship_value = map[string]int32{
		"SCHEDULED": 0,
		"SKIPPED":   1,
		"NO_DATA":   2,
	}
)

func (x TripUpdate_StopTimeUpdate_ScheduleRelationship) Enum() *TripUpdate_StopTimeUpdate_ScheduleRelationship {
	p := new(TripUpdate_StopTimeUpdate_ScheduleRelationship)
	*p = x
	return p
}

func (x TripUpdate_StopTimeUpdate_ScheduleRelationship) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TripUpdate_StopTimeUpdate_ScheduleRelationship) Descriptor() protoreflect.EnumDescriptor {
	return file_gtfs_realtime_proto_enumTypes[1].Descriptor()
}

func (TripUpdate_StopTimeUpdate_ScheduleRelationship) Type() protoreflect.EnumType {
	return &file_gtfs_realtime_proto_enumTypes[1]
}

func (x TripUpdate_StopTimeUpdate_ScheduleRelationship) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *TripUpdate_StopTimeUpdate_ScheduleRelationship) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = TripUpdate_StopTimeUpdate_ScheduleRelationship(num)
	return nil
}

// Deprecated: Use TripUpdate_StopTimeUpdate_ScheduleRelationship.Descriptor instead.
func (TripUpdate_StopTimeUpdate_ScheduleRelationship) EnumDescriptor() ([]byte, []int) {
	return file_gtfs_realtime_proto_rawDescGZIP(), []int{3, 1, 0}
}

type VehiclePosition_VehicleStopStatus int32

const (
	VehiclePosition_INCOMING_AT   VehiclePosition_VehicleStopStatus = 0
	VehiclePosition_STOPPED_AT    VehiclePosition_VehicleStopStatus = 1
	VehiclePosition_IN_TRANSIT_TO VehiclePosition_VehicleStopStatus = 2
)

// Enum value maps for VehiclePosition_VehicleStopStatus.
var (
	VehiclePosition_VehicleStopStatus_name = map[int32]string{
		0: "INCOMING_AT",
		1: "STOPPED_AT",
		2: "IN_TRANSIT_TO",
	}
	VehiclePosition_VehicleStopStatus_value = map[string]int32{
		"INCOMING_AT":   0,
		"STOPPED_AT":    1,
		"IN_TRANSIT_TO": 2,
	}
)

func (x VehiclePosition_VehicleStopStatus) Enum() *VehiclePosition_VehicleStopStatus {
	p := new(VehiclePosition_VehicleStopStatus)
	*p = x
	return p
}

func (x VehiclePosition_VehicleStopStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VehiclePosition_VehicleStopStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_gtfs_realtime_proto_enumTypes[2].Descriptor()
}

func (VehiclePosition_VehicleStopStatus) Type() protoreflect.EnumType {
	return &file_gtfs_realtime_proto_enumTypes[2]
}

func (x VehiclePosition_VehicleStopStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *VehiclePosition_VehicleStopStatus) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = VehiclePosition_VehicleStopStatus(num)
	return nil
}

// Deprecated: Use VehiclePosition_VehicleStopStatus.Descriptor instead.
func (VehiclePosition_VehicleStopStatus) EnumDescriptor() ([]byte, []int) {
	return file_gtfs_realtime_proto_rawDescGZIP(), []int{4, 0}
}

type VehiclePosition_CongestionLevel int32

const (
	VehiclePosition_UNKNOWN_CONGESTION_LEVEL VehiclePosition_CongestionLevel = 0
	VehiclePosition_RUNNING_SMOOTHLY         VehiclePosition_CongestionLevel = 1
	VehiclePosition_STOP_AND_GO              VehiclePosition_CongestionLevel = 2
	VehiclePosition_CONGESTION               VehiclePosition_CongestionLevel = 3
	VehiclePosition_SEVERE_CONGESTION        VehiclePosition_CongestionLevel = 4
)

// Enum value maps for VehiclePosition_CongestionLevel.
var (
	VehiclePosition_CongestionLevel_name = map[int32]string{
		0: "UNKNOWN_CONGESTION_LEVEL",
		1: "RUNNING_SMOOTHLY",
		2: "STOP_AND_GO",
		3: "CONGESTION",
		4: "SEVERE_CONGESTION",
	}
	VehiclePosition_CongestionLevel_value = map[string]int32{
		"UNKNOWN_CONGESTION_LEVEL": 0,
		"RUNNING_SMOOTHLY":         1,
		"STOP_AND_GO":              2,
		"CONGESTION":               3,
		"SEVERE_CONGESTION":        4,
	}
)

func (x VehiclePosition_CongestionLevel) Enum() *VehiclePosition_CongestionLevel {
	p := new(VehiclePosition_CongestionLevel)
	*p = x
	return p
}

func (x VehiclePosition_CongestionLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VehiclePosition_CongestionLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_gtfs_realtime_proto_enumTypes[3].Descriptor()
}

func (VehiclePosition_CongestionLevel) Type() protoreflect.EnumType {
	return &file_gtfs_realtime_proto_enumTypes[3]
}

func (x VehiclePosition_CongestionLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *VehiclePosition_CongestionLevel) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = VehiclePosition_CongestionLevel(num)
	return nil
}

// Deprecated: Use VehiclePosition_CongestionLevel.Descriptor instead.
func (VehiclePosition_CongestionLevel) EnumDescriptor() ([]byte, []int) {
	return file_gtfs_realtime_proto_rawDescGZIP(), []int{4, 1}
}

type VehiclePosition_OccupancyStatus int32

const (
	VehiclePosition_EMPTY                      VehiclePosition_OccupancyStatus = 0
	VehiclePosition_MANY_SEATS_AVAILABLE       VehiclePosition_OccupancyStatus = 1
	VehiclePosition_FEW_SEATS_AVAILABLE        VehiclePosition_OccupancyStatus = 2
	VehiclePosition_STANDING_ROOM_ONLY         VehiclePosition_OccupancyStatus = 3
	VehiclePosition_CRUSHED_STANDING_ROOM_ONLY VehiclePosition_OccupancyStatus = 4
	VehiclePosition_FULL                       VehiclePosition_OccupancyStatus = 5
	VehiclePosition_NOT_ACCEPTING_PASSENGERS   VehiclePosition_OccupancyStatus = 6
)

// Enum value maps for VehiclePosition_OccupancyStatus.
var (
	VehiclePosition_OccupancyStatus_name = map[int32]string{
		0: "EMPTY",
		1: "MANY_SEATS_AVAILABLE",
		2: "FEW_SEATS_AVAILABLE",
		3: "STANDING_ROOM_ONLY",
		4: "CRUSHED_STANDING_ROOM_ONLY",
		5: "FULL",
		6: "NOT_ACCEPTING_PASSENGERS",
	}
	VehiclePosition_OccupancyStatus_value = map[string]int32{
		"EMPTY":                      0,
		"MANY_SEATS_AVAILABLE":       1,
		"FEW_SEATS_AVAILABLE":        2,
		"STANDING_ROOM_ONLY":         3,
		"CRUSHED_STANDING_ROOM_ONLY": 4,
		"FULL":                       5,
		"NOT_ACCEPTING_PASSENGERS":   6,
	}
)

func (x VehiclePosition_OccupancyStatus) Enum() *VehiclePosition_OccupancyStatus {
	p := new(VehiclePosition_OccupancyStatus)
	*p = x
	return p
}

func (x VehiclePosition_OccupancyStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VehiclePosition_OccupancyStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_gtfs_realtime_proto_enumTypes[4].Descriptor()
}

func (VehiclePosition_OccupancyStatus) Type() protoreflect.EnumType {
	return &file_gtfs_realtime_proto_enumTypes[4]
}

func (x VehiclePosition_OccupancyStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *VehiclePosition_OccupancyStatus) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = VehiclePosition_OccupancyStatus(num)
	return nil
}

// Deprecated: Use VehiclePosition_OccupancyStatus.Descriptor instead.
func (VehiclePosition_OccupancyStatus) EnumDescriptor() ([]byte, []int) {
	return file_gtfs_realtime_proto_rawDescGZIP(), []int{4, 2}
}

type Alert_Cause int32

const (
	Alert_UNKNOWN_CAUSE     Alert_Cause = 1
	Alert_OTHER_CAUSE       Alert_Cause = 2
	Alert_TECHNICAL_PROBLEM Alert_Cause = 3
	Alert_STRIKE            Alert_Cause = 4
	Alert_DEMONSTRATION     Alert_Cause = 5
	Alert_ACCIDENT          Alert_Cause = 6
	Alert_HOLIDAY           Alert_Cause = 7
	Alert_WEATHER           Alert_Cause = 8
	Alert_MAINTENANCE       Alert_Cause = 9
	Alert_CONSTRUCTION      Alert_Cause = 10
	Alert_POLICE_ACTIVITY   Alert_Cause = 11
	Alert_MEDICAL_EMERGENCY Alert_Cause = 12
)

// Enum value maps for Alert_Cause.
var (
	Alert_Cause_name = map[int32]string{
		1:  "UNKNOWN_CAUSE",
		2:  "OTHER_CAUSE",
		3:  "TECHNICAL_PROBLEM",
		4:  "STRIKE",
		5:  "DEMONSTRATION",
		6:  "ACCIDENT",
		7:  "HOLIDAY",
		8:  "WEATHER",
		9:  "MAINTENANCE",
		10: "CONSTRUCTION",
		11: "POLICE_ACTIVITY",
		12: "MEDICAL_EMERGENCY",
	}
	Alert_Cause_value = map[string]int32{
		"UNKNOWN_CAUSE":     1,
		"OTHER_CAUSE":       2,
		"TECHNICAL_PROBLEM": 3,
		"STRIKE":            4,
		"DEMONSTRATION":     5,
		"ACCIDENT":          6,
		"HOLIDAY":           7,
		"WEATHER":           8,
		"MAINTENANCE":       9,
		"CONSTRUCTION":      10,
		"POLICE_ACTIVITY":   11,
		"MEDICAL_EMERGENCY": 12,
	}
)

func (x Alert_Cause) Enum() *Alert_Cause {
	p := new(Alert_Cause)
	*p = x
	return p
}

func (x Alert_Cause) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Alert_Cause) Descriptor() protoreflect.EnumDescriptor {
	return file_gtfs_realtime_proto_enumTypes[5].Descriptor()
}

func (Alert_Cause) Type() protoreflect.EnumType {
	return &file_gtfs_realtime_proto_enumTypes[5]
}

func (x Alert_Cause) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Alert_Cause) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Alert_Cause(num)
	return nil
}

// Deprecated: Use Alert_Cause.Descriptor instead.
func (Alert_Cause) EnumDescriptor() ([]byte, []int) {
	return file_gtfs_realtime_proto_rawDescGZIP(), []int{5, 0}
}

type Alert_Effect int32

const (
	Alert_NO_SERVICE         Alert_Effect = 1
	Alert_REDUCED_SERVICE    Alert_Effect = 2
	Alert_SIGNIFICANT_DELAYS Alert_Effect = 3
	Alert_DETOUR             Alert_Effect = 4
	Alert_ADDITIONAL_SERVICE Alert_Effect = 5
	Alert_MODIFIED_SERVICE   Alert_Effect = 6
	Alert_OTHER_EFFECT       Alert_Effect = 7
	Alert_UNKNOWN_EFFECT     Alert_Effect = 8
	Alert_STOP_MOVED         Alert_Effect = 9
)

// Enum value maps for Alert_Effect.
var (
	Alert_Effect_name = map[int32]string{
		1: "NO_SERVICE",
		2: "REDUCED_SERVICE",
		3: "SIGNIFICANT_DELAYS",
		4: "DETOUR",
		5: "ADDITIONAL_SERVICE",
		6: "MODIFIED_SERVICE",
		7: "OTHER_EFFECT",
		8: "UNKNOWN_EFFECT",
		9: "STOP_MOVED",
	}
	Alert_Effect_value = map[string]int32{
		"NO_SERVICE":         1,
		"REDUCED_SERVICE":    2,
		"SIGNIFICANT_DELAYS": 3,
		"DETOUR":             4,
		"ADDITIONAL_SERVICE": 5,
		"MODIFIED_SERVICE":   6,
		"OTHER_EFFECT":       7,
		"UNKNOWN_EFFECT":     8,
		"STOP_MOVED":         9,
	}
)

func (x Alert_Effect) Enum() *Alert_Effect {
	p := new(Alert_Effect)
	*p = x
	return p
}

func (x Alert_Effect) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Alert_Effect) Descriptor() protoreflect.EnumDescriptor {
	return file_gtfs_realtime_proto_enumTypes[6].Descriptor()
}

func (Alert_Effect) Type() protoreflect.EnumType {
	return &file_gtfs_realtime_proto_enumTypes[6]
}

func (x Alert_Effect) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Alert_Effect) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Alert_Effect(num)
	return nil
}

// Deprecated: Use Alert_Effect.Descriptor instead.
func (Alert_Effect) EnumDescriptor() ([]byte, []int) {
	return file_gtfs_realtime_proto_rawDescGZIP(), []int{5, 1}
}

type TripDescriptor_ScheduleRelationship int32

const (
	TripDescriptor_SCHEDULED   TripDescriptor_ScheduleRelationship = 0
	TripDescriptor_ADDED       TripDescriptor_ScheduleRelationship = 1
	TripDescriptor_UNSCHEDULED TripDescriptor_ScheduleRelationship = 2
	TripDescriptor_CANCELED    TripDescriptor_ScheduleRelationship = 3
)

// Enum value maps for TripDescriptor_ScheduleRelationship.
var (
	TripDescriptor_ScheduleRelationship_name = map[int32]string{
		0: "SCHEDULED",
		1: "ADDED",
		2: "UNSCHEDULED",
		3: "CANCELED",
	}
	TripDescriptor_ScheduleRelationship_value = map[string]int32{
		"SCHEDULED":   0,
		"ADDED":       1,
		"UNSCHEDULED": 2,
		"CANCELED":    3,
	}
)

func (x TripDescriptor_ScheduleRelationship) Enum() *TripDescriptor_ScheduleRelationship {
	p := new(TripDescriptor_ScheduleRelationship)
	*p = x
	return p
}

func (x TripDescriptor_ScheduleRelationship) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TripDescriptor_ScheduleRelationship) Descriptor() protoreflect.EnumDescriptor {
	return file_gtfs_realtime_proto_enumTypes[7].Descriptor()
}

func (TripDescriptor_ScheduleRelationship) Type() protoreflect.EnumType {
	return &file_gtfs_realtime_proto_enumTypes[7]
}

func (x TripDescriptor_ScheduleRelationship) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *TripDescriptor_ScheduleRelationship) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = TripDescriptor_ScheduleRelationship(num)
	return nil
}

// Deprecated: Use TripDescriptor_ScheduleRelationship.Descriptor instead.
func (TripDescriptor_ScheduleRelationship) EnumDescriptor() ([]byte, []int) {
	return file_gtfs_realtime_proto_rawDescGZIP(), []int{8, 0}
}

type FeedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *FeedHeader            `protobuf:"bytes,1,req,name=header" json:"header,omitempty"`
	Entity        []*FeedEntity          `protobuf:"bytes,2,rep,name=entity" json:"entity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedMessage) Reset() {
	*x = FeedMessage{}
	mi := &file_gtfs_realtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedMessage) ProtoMessage() {}

func (x *FeedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_gtfs_realtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedMessage.ProtoReflect.Descriptor instead.
func (*FeedMessage) Descriptor() ([]byte, []int) {
	return file_gtfs_realtime_proto_rawDescGZIP(), []int{0}
}

func (x *FeedMessage) GetHeader() *FeedHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *FeedMessage) GetEntity() []*FeedEntity {
	if x != nil {
		return x.Entity
	}
	return nil
}

type FeedHeader struct {
	state               protoimpl.MessageState     `protogen:"open.v1"`
	GtfsRealtimeVersion *string                    `protobuf:"bytes,1,req,name=gtfs_realtime_version,json=gtfsRealtimeVersion" json:"gtfs_realtime_version,omitempty"`
	Incrementality      *FeedHeader_Incrementality `protobuf:"varint,2,opt,name=incrementality,enum=transit_realtime.FeedHeader_Incrementality,def=0" json:"incrementality,omitempty"`
	Timestamp           *uint64                    `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

// Default values for FeedHeader fields.
const (
	Default_FeedHeader_Incrementality = FeedHeader_FULL_DATASET
)

func (x *FeedHeader) Reset() {
	*x = FeedHeader{}
	mi := &file_gtfs_realtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedHeader) ProtoMessage() {}

func (x *FeedHeader) ProtoReflect() protoreflect.Message {
	mi := &file_gtfs_realtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedHeader.ProtoReflect.Descriptor instead.
func (*FeedHeader) Descriptor() ([]byte, []int) {
	return file_gtfs_realtime_proto_rawDescGZIP(), []int{1}
}

func (x *FeedHeader) GetGtfsRealtimeVersion() string {
	if x != nil && x.GtfsRealtimeVersion != nil {
		return *x.GtfsRealtimeVersion
	}
	return ""
}

func (x *FeedHeader) GetIncrementality() FeedHeader_Incrementality {
	if x != nil && x.Incrementality != nil {
		return *x.Incrementality
	}
	return Default_FeedHeader_Incrementality
}

func (x *FeedHeader) GetTimestamp() uint64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

type FeedEntity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	IsDeleted     *bool                  `protobuf:"varint,2,opt,name=is_deleted,json=isDeleted,def=0" json:"is_deleted,omitempty"`
	TripUpdate    *TripUpdate            `protobuf:"bytes,3,opt,name=trip_update,json=tripUpdate" json:"trip_update,omitempty"`
	Vehicle       *VehiclePosition       `protobuf:"bytes,4,opt,name=vehicle" json:"vehicle,omitempty"`
	Alert         *Alert                 `protobuf:"bytes,5,opt,name=alert" json:"alert,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for FeedEntity fields.
const (
	Default_FeedEntity_IsDeleted = bool(false)
)

func (x *FeedEntity) Reset() {
	*x = FeedEntity{}
	mi := &file_gtfs_realtime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedEntity) ProtoMessage() {}

func (x *FeedEntity) ProtoReflect() protoreflect.Message {
	mi := &file_gtfs_realtime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedEntity.ProtoReflect.Descriptor instead.
func (*FeedEntity) Descriptor() ([]byte, []int) {
	return file_gtfs_realtime_proto_rawDescGZIP(), []int{2}
}

func (x *FeedEntity) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *FeedEntity) GetIsDeleted() bool {
	if x != nil && x.IsDeleted != nil {
		return *x.IsDeleted
	}
	return Default_FeedEntity_IsDeleted
}

func (x *FeedEntity) GetTripUpdate() *TripUpdate {
	if x != nil {
		return x.TripUpdate
	}
	return nil
}

func (x *FeedEntity) GetVehicle() *VehiclePosition {
	if x != nil {
		return x.Vehicle
	}
	return nil
}

func (x *FeedEntity) GetAlert() *Alert {
	if x != nil {
		return x.Alert
	}
	return nil
}

type TripUpdate struct {
	state          protoimpl.MessageState       `protogen:"open.v1"`
	Trip           *TripDescriptor              `protobuf:"bytes,1,req,name=trip" json:"trip,omitempty"`
	Vehicle        *VehicleDescriptor           `protobuf:"bytes,3,opt,name=vehicle" json:"vehicle,omitempty"`
	StopTimeUpdate []*TripUpdate_StopTimeUpdate `protobuf:"bytes,2,rep,name=stop_time_update,json=stopTimeUpdate" json:"stop_time_update,omitempty"`
	Timestamp      *uint64                      `protobuf:"varint,4,opt,name=timestamp" json:"timestamp,omitempty"`
	Delay          *int32                       `protobuf:"varint,5,opt,name=delay" json:"delay,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TripUpdate) Reset() {
	*x = TripUpdate{}
	mi := &file_gtfs_realtime_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TripUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripUpdate) ProtoMessage() {}

func (x *TripUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_gtfs_realtime_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripUpdate.ProtoReflect.Descriptor instead.
func (*TripUpdate) Descriptor() ([]byte, []int) {
	return file_gtfs_realtime_proto_rawDescGZIP(), []int{3}
}

func (x *TripUpdate) GetTrip() *TripDescriptor {
	if x != nil {
		return x.Trip
	}
	return nil
}

func (x *TripUpdate) GetVehicle() *VehicleDescriptor {
	if x != nil {
		return x.Vehicle
	}
	return nil
}

func (x *TripUpdate) GetStopTimeUpdate() []*TripUpdate_StopTimeUpdate {
	if x != nil {
		return x.StopTimeUpdate
	}
	return nil
}

func (x *TripUpdate) GetTimestamp() uint64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *TripUpdate) GetDelay() int32 {
	if x != nil && x.Delay != nil {
		return *x.Delay
	}
	return 0
}

type VehiclePosition struct {
	state               protoimpl.MessageState             `protogen:"open.v1"`
	Trip                *TripDescriptor                    `protobuf:"bytes,1,opt,name=trip" json:"trip,omitempty"`
	Vehicle             *VehicleDescriptor                 `protobuf:"bytes,8,opt,name=vehicle" json:"vehicle,omitempty"`
	Position            *Position                          `protobuf:"bytes,2,opt,name=position" json:"position,omitempty"`
	CurrentStopSequence *uint32                            `protobuf:"varint,3,opt,name=current_stop_sequence,json=currentStopSequence" json:"current_stop_sequence,omitempty"`
	StopId              *string                            `protobuf:"bytes,7,opt,name=stop_id,json=stopId" json:"stop_id,omitempty"`
	CurrentStatus       *VehiclePosition_VehicleStopStatus `protobuf:"varint,4,opt,name=current_status,json=currentStatus,enum=transit_realtime.VehiclePosition_VehicleStopStatus,def=2" json:"current_status,omitempty"`
	Timestamp           *uint64                            `protobuf:"varint,5,opt,name=timestamp" json:"timestamp,omitempty"`
	CongestionLevel     *VehiclePosition_CongestionLevel   `protobuf:"varint,6,opt,name=congestion_level,json=congestionLevel,enum=transit_realtime.VehiclePosition_CongestionLevel" json:"congestion_level,omitempty"`
	OccupancyStatus     *VehiclePosition_OccupancyStatus   `protobuf:"varint,9,opt,name=occupancy_status,json=occupancyStatus,enum=transit_realtime.VehiclePosition_OccupancyStatus" json:"occupancy_status,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

// Default values for VehiclePosition fields.
const (
	Default_VehiclePosition_CurrentStatus = VehiclePosition_IN_TRANSIT_TO
)

func (x *VehiclePosition) Reset() {
	*x = VehiclePosition{}
	mi := &file_gtfs_realtime_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehiclePosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehiclePosition) ProtoMessage() {}

func (x *VehiclePosition) ProtoReflect() protoreflect.Message {
	mi := &file_gtfs_realtime_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehiclePosition.ProtoReflect.Descriptor instead.
func (*VehiclePosition) Descriptor() ([]byte, []int) {
	return file_gtfs_realtime_proto_rawDescGZIP(), []int{4}
}

func (x *VehiclePosition) GetTrip() *TripDescriptor {
	if x != nil {
		return x.Trip
	}
	return nil
}

func (x *VehiclePosition) GetVehicle() *VehicleDescriptor {
	if x != nil {
		return x.Vehicle
	}
	return nil
}

func (x *VehiclePosition) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *VehiclePosition) GetCurrentStopSequence() uint32 {
	if x != nil && x.CurrentStopSequence != nil {
		return *x.CurrentStopSequence
	}
	return 0
}

func (x *VehiclePosition) GetStopId() string {
	if x != nil && x.StopId != nil {
		return *x.StopId
	}
	return ""
}

func (x *VehiclePosition) GetCurrentStatus() VehiclePosition_VehicleStopStatus {
	if x != nil && x.CurrentStatus != nil {
		return *x.CurrentStatus
	}
	return Default_VehiclePosition_CurrentStatus
}

func (x *VehiclePosition) GetTimestamp() uint64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *VehiclePosition) GetCongestionLevel() VehiclePosition_CongestionLevel {
	if x != nil && x.CongestionLevel != nil {
		return *x.CongestionLevel
	}
	return VehiclePosition_UNKNOWN_CONGESTION_LEVEL
}

func (x *VehiclePosition) GetOccupancyStatus() VehiclePosition_OccupancyStatus {
	if x != nil && x.OccupancyStatus != nil {
		return *x.OccupancyStatus
	}
	return VehiclePosition_EMPTY
}

type Alert struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ActivePeriod    []*TimeRange           `protobuf:"bytes,1,rep,name=active_period,json=activePeriod" json:"active_period,omitempty"`
	InformedEntity  []*EntitySelector      `protobuf:"bytes,5,rep,name=informed_entity,json=informedEntity" json:"informed_entity,omitempty"`
	Cause           *Alert_Cause           `protobuf:"varint,6,opt,name=cause,enum=transit_realtime.Alert_Cause,def=1" json:"cause,omitempty"`
	Effect          *Alert_Effect          `protobuf:"varint,7,opt,name=effect,enum=transit_realtime.Alert_Effect,def=8" json:"effect,omitempty"`
	Url             *TranslatedString      `protobuf:"bytes,8,opt,name=url" json:"url,omitempty"`
	HeaderText      *TranslatedString      `protobuf:"bytes,10,opt,name=header_text,json=headerText" json:"header_text,omitempty"`
	DescriptionText *TranslatedString      `protobuf:"bytes,11,opt,name=description_text,json=descriptionText" json:"description_text,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

// Default values for Alert fields.
const (
	Default_Alert_Cause  = Alert_UNKNOWN_CAUSE
	Default_Alert_Effect = Alert_UNKNOWN_EFFECT
)

func (x *Alert) Reset() {
	*x = Alert{}
	mi := &file_gtfs_realtime_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_gtfs_realtime_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_gtfs_realtime_proto_rawDescGZIP(), []int{5}
}

func (x *Alert) GetActivePeriod() []*TimeRange {
	if x != nil {
		return x.ActivePeriod
	}
	return nil
}

func (x *Alert) GetInformedEntity() []*EntitySelector {
	if x != nil {
		return x.InformedEntity
	}
	return nil
}

func (x *Alert) GetCause() Alert_Cause {
	if x != nil && x.Cause != nil {
		return *x.Cause
	}
	return Default_Alert_Cause
}

func (x *Alert) GetEffect() Alert_Effect {
	if x != nil && x.Effect != nil {
		return *x.Effect
	}
	return Default_Alert_Effect
}

func (x *Alert) GetUrl() *TranslatedString {
	if x != nil {
		return x.Url
	}
	return nil
}

func (x *Alert) GetHeaderText() *TranslatedString {
	if x != nil {
		return x.HeaderText
	}
	return nil
}

func (x *Alert) GetDescriptionText() *TranslatedString {
	if x != nil {
		return x.DescriptionText
	}
	return nil
}

type TimeRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         *uint64                `protobuf:"varint,1,opt,name=start" json:"start,omitempty"`
	End           *uint64                `protobuf:"varint,2,opt,name=end" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeRange) Reset() {
	*x = TimeRange{}
	mi := &file_gtfs_realtime_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeRange) ProtoMessage() {}

func (x *TimeRange) ProtoReflect() protoreflect.Message {
	mi := &file_gtfs_realtime_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeRange.ProtoReflect.Descriptor instead.
func (*TimeRange) Descriptor() ([]byte, []int) {
	return file_gtfs_realtime_proto_rawDescGZIP(), []int{6}
}

func (x *TimeRange) GetStart() uint64 {
	if x != nil && x.Start != nil {
		return *x.Start
	}
	return 0
}

func (x *TimeRange) GetEnd() uint64 {
	if x != nil && x.End != nil {
		return *x.End
	}
	return 0
}

type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      *float32               `protobuf:"fixed32,1,req,name=latitude" json:"latitude,omitempty"`
	Longitude     *float32               `protobuf:"fixed32,2,req,name=longitude" json:"longitude,omitempty"`
	Bearing       *float32               `protobuf:"fixed32,3,opt,name=bearing" json:"bearing,omitempty"`
	Odometer      *float64               `protobuf:"fixed64,4,opt,name=odometer" json:"odometer,omitempty"`
	Speed         *float32               `protobuf:"fixed32,5,opt,name=speed" json:"speed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_gtfs_realtime_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_gtfs_realtime_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_gtfs_realtime_proto_rawDescGZIP(), []int{7}
}

func (x *Position) GetLatitude() float32 {
	if x != nil && x.Latitude != nil {
		return *x.Latitude
	}
	return 0
}

func (x *Position) GetLongitude() float32 {
	if x != nil && x.Longitude != nil {
		return *x.Longitude
	}
	return 0
}

func (x *Position) GetBearing() float32 {
	if x != nil && x.Bearing != nil {
		return *x.Bearing
	}
	return 0
}

func (x *Position) GetOdometer() float64 {
	if x != nil && x.Odometer != nil {
		return *x.Odometer
	}
	return 0
}

func (x *Position) GetSpeed() float32 {
	if x != nil && x.Speed != nil {
		return *x.Speed
	}
	return 0
}

type TripDescriptor struct {
	state                protoimpl.MessageState               `protogen:"open.v1"`
	TripId               *string                              `protobuf:"bytes,1,opt,name=trip_id,json=tripId" json:"trip_id,omitempty"`
	RouteId              *string                              `protobuf:"bytes,5,opt,name=route_id,json=routeId" json:"route_id,omitempty"`
	DirectionId          *uint32                              `protobuf:"varint,6,opt,name=direction_id,json=directionId" json:"direction_id,omitempty"`
	StartTime            *string                              `protobuf:"bytes,2,opt,name=start_time,json=startTime" json:"start_time,omitempty"`
	StartDate            *string                              `protobuf:"bytes,3,opt,name=start_date,json=startDate" json:"start_date,omitempty"`
	ScheduleRelationship *TripDescriptor_ScheduleRelationship `protobuf:"varint,4,opt,name=schedule_relationship,json=scheduleRelationship,enum=transit_realtime.TripDescriptor_ScheduleRelationship" json:"schedule_relationship,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TripDescriptor) Reset() {
	*x = TripDescriptor{}
	mi := &file_gtfs_realtime_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TripDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripDescriptor) ProtoMessage() {}

func (x *TripDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_gtfs_realtime_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripDescriptor.ProtoReflect.Descriptor instead.
func (*TripDescriptor) Descriptor() ([]byte, []int) {
	return file_gtfs_realtime_proto_rawDescGZIP(), []int{8}
}

func (x *TripDescriptor) GetTripId() string {
	if x != nil && x.TripId != nil {
		return *x.TripId
	}
	return ""
}

func (x *TripDescriptor) GetRouteId() string {
	if x != nil && x.RouteId != nil {
		return *x.RouteId
	}
	return ""
}

func (x *TripDescriptor) GetDirectionId() uint32 {
	if x != nil && x.DirectionId != nil {
		return *x.DirectionId
	}
	return 0
}

func (x *TripDescriptor) GetStartTime() string {
	if x != nil && x.StartTime != nil {
		return *x.StartTime
	}
	return ""
}

func (x *TripDescriptor) GetStartDate() string {
	if x != nil && x.StartDate != nil {
		return *x.StartDate
	}
	return ""
}

func (x *TripDescriptor) GetScheduleRelationship() TripDescriptor_ScheduleRelationship {
	if x != nil && x.ScheduleRelationship != nil {
		return *x.ScheduleRelationship
	}
	return TripDescriptor_SCHEDULED
}

type VehicleDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Label         *string                `protobuf:"bytes,2,opt,name=label" json:"label,omitempty"`
	LicensePlate  *string                `protobuf:"bytes,3,opt,name=license_plate,json=licensePlate" json:"license_plate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VehicleDescriptor) Reset() {
	*x = VehicleDescriptor{}
	mi := &file_gtfs_realtime_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleDescriptor) ProtoMessage() {}

func (x *VehicleDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_gtfs_realtime_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleDescriptor.ProtoReflect.Descriptor instead.
func (*VehicleDescriptor) Descriptor() ([]byte, []int) {
	return file_gtfs_realtime_proto_rawDescGZIP(), []int{9}
}

func (x *VehicleDescriptor) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *VehicleDescriptor) GetLabel() string {
	if x != nil && x.Label != nil {
		return *x.Label
	}
	return ""
}

func (x *VehicleDescriptor) GetLicensePlate() string {
	if x != nil && x.LicensePlate != nil {
		return *x.LicensePlate
	}
	return ""
}

type EntitySelector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgencyId      *string                `protobuf:"bytes,1,opt,name=agency_id,json=agencyId" json:"agency_id,omitempty"`
	RouteId       *string                `protobuf:"bytes,2,opt,name=route_id,json=routeId" json:"route_id,omitempty"`
	RouteType     *int32                 `protobuf:"varint,3,opt,name=route_type,json=routeType" json:"route_type,omitempty"`
	Trip          *TripDescriptor        `protobuf:"bytes,4,opt,name=trip" json:"trip,omitempty"`
	StopId        *string                `protobuf:"bytes,5,opt,name=stop_id,json=stopId" json:"stop_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntitySelector) Reset() {
	*x = EntitySelector{}
	mi := &file_gtfs_realtime_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntitySelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntitySelector) ProtoMessage() {}

func (x *EntitySelector) ProtoReflect() protoreflect.Message {
	mi := &file_gtfs_realtime_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntitySelector.ProtoReflect.Descriptor instead.
func (*EntitySelector) Descriptor() ([]byte, []int) {
	return file_gtfs_realtime_proto_rawDescGZIP(), []int{10}
}

func (x *EntitySelector) GetAgencyId() string {
	if x != nil && x.AgencyId != nil {
		return *x.AgencyId
	}
	return ""
}

func (x *EntitySelector) GetRouteId() string {
	if x != nil && x.RouteId != nil {
		return *x.RouteId
	}
	return ""
}

func (x *EntitySelector) GetRouteType() int32 {
	if x != nil && x.RouteType != nil {
		return *x.RouteType
	}
	return 0
}

func (x *EntitySelector) GetTrip() *TripDescriptor {
	if x != nil {
		return x.Trip
	}
	return nil
}

func (x *EntitySelector) GetStopId() string {
	if x != nil && x.StopId != nil {
		return *x.StopId
	}
	return ""
}

type TranslatedString struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Translation   []*TranslatedString_Translation `protobuf:"bytes,1,rep,name=translation" json:"translation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranslatedString) Reset() {
	*x = TranslatedString{}
	mi := &file_gtfs_realtime_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslatedString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslatedString) ProtoMessage() {}

func (x *TranslatedString) ProtoReflect() protoreflect.Message {
	mi := &file_gtfs_realtime_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslatedString.ProtoReflect.Descriptor instead.
func (*TranslatedString) Descriptor() ([]byte, []int) {
	return file_gtfs_realtime_proto_rawDescGZIP(), []int{11}
}

func (x *TranslatedString) GetTranslation() []*TranslatedString_Translation {
	if x != nil {
		return x.Translation
	}
	return nil
}

type TripUpdate_StopTimeEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delay         *int32                 `protobuf:"varint,1,opt,name=delay" json:"delay,omitempty"`
	Time          *int64                 `protobuf:"varint,2,opt,name=time" json:"time,omitempty"`
	Uncertainty   *int32                 `protobuf:"varint,3,opt,name=uncertainty" json:"uncertainty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TripUpdate_StopTimeEvent) Reset() {
	*x = TripUpdate_StopTimeEvent{}
	mi := &file_gtfs_realtime_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TripUpdate_StopTimeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripUpdate_StopTimeEvent) ProtoMessage() {}

func (x *TripUpdate_StopTimeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_gtfs_realtime_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripUpdate_StopTimeEvent.ProtoReflect.Descriptor instead.
func (*TripUpdate_StopTimeEvent) Descriptor() ([]byte, []int) {
	return file_gtfs_realtime_proto_rawDescGZIP(), []int{3, 0}
}

func (x *TripUpdate_StopTimeEvent) GetDelay() int32 {
	if x != nil && x.Delay != nil {
		return *x.Delay
	}
	return 0
}

func (x *TripUpdate_StopTimeEvent) GetTime() int64 {
	if x != nil && x.Time != nil {
		return *x.Time
	}
	return 0
}

func (x *TripUpdate_StopTimeEvent) GetUncertainty() int32 {
	if x != nil && x.Uncertainty != nil {
		return *x.Uncertainty
	}
	return 0
}

type TripUpdate_StopTimeUpdate struct {
	state                protoimpl.MessageState                          `protogen:"open.v1"`
	StopSequence         *uint32                                         `protobuf:"varint,1,opt,name=stop_sequence,json=stopSequence" json:"stop_sequence,omitempty"`
	StopId               *string                                         `protobuf:"bytes,4,opt,name=stop_id,json=stopId" json:"stop_id,omitempty"`
	Arrival              *TripUpdate_StopTimeEvent                       `protobuf:"bytes,2,opt,name=arrival" json:"arrival,omitempty"`
	Departure            *TripUpdate_StopTimeEvent                       `protobuf:"bytes,3,opt,name=departure" json:"departure,omitempty"`
	ScheduleRelationship *TripUpdate_StopTimeUpdate_ScheduleRelationship `protobuf:"varint,5,opt,name=schedule_relationship,json=scheduleRelationship,enum=transit_realtime.TripUpdate_StopTimeUpdate_ScheduleRelationship,def=0" json:"schedule_relationship,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

// Default values for TripUpdate_StopTimeUpdate fields.
const (
	Default_TripUpdate_StopTimeUpdate_ScheduleRelationship = TripUpdate_StopTimeUpdate_SCHEDULED
)

func (x *TripUpdate_StopTimeUpdate) Reset() {
	*x = TripUpdate_StopTimeUpdate{}
	mi := &file_gtfs_realtime_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TripUpdate_StopTimeUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripUpdate_StopTimeUpdate) ProtoMessage() {}

func (x *TripUpdate_StopTimeUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_gtfs_realtime_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripUpdate_StopTimeUpdate.ProtoReflect.Descriptor instead.
func (*TripUpdate_StopTimeUpdate) Descriptor() ([]byte, []int) {
	return file_gtfs_realtime_proto_rawDescGZIP(), []int{3, 1}
}

func (x *TripUpdate_StopTimeUpdate) GetStopSequence() uint32 {
	if x != nil && x.StopSequence != nil {
		return *x.StopSequence
	}
	return 0
}

func (x *TripUpdate_StopTimeUpdate) GetStopId() string {
	if x != nil && x.StopId != nil {
		return *x.StopId
	}
	return ""
}

func (x *TripUpdate_StopTimeUpdate) GetArrival() *TripUpdate_StopTimeEvent {
	if x != nil {
		return x.Arrival
	}
	return nil
}

func (x *TripUpdate_StopTimeUpdate) GetDeparture() *TripUpdate_StopTimeEvent {
	if x != nil {
		return x.Departure
	}
	return nil
}

func (x *TripUpdate_StopTimeUpdate) GetScheduleRelationship() TripUpdate_StopTimeUpdate_ScheduleRelationship {
	if x != nil && x.ScheduleRelationship != nil {
		return *x.ScheduleRelationship
	}
	return Default_TripUpdate_StopTimeUpdate_ScheduleRelationship
}

type TranslatedString_Translation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          *string                `protobuf:"bytes,1,req,name=text" json:"text,omitempty"`
	Language      *string                `protobuf:"bytes,2,opt,name=language" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranslatedString_Translation) Reset() {
	*x = TranslatedString_Translation{}
	mi := &file_gtfs_realtime_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslatedString_Translation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslatedString_Translation) ProtoMessage() {}

func (x *TranslatedString_Translation) ProtoReflect() protoreflect.Message {
	mi := &file_gtfs_realtime_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslatedString_Translation.ProtoReflect.Descriptor instead.
func (*TranslatedString_Translation) Descriptor() ([]byte, []int) {
	return file_gtfs_realtime_proto_rawDescGZIP(), []int{11, 0}
}

func (x *TranslatedString_Translation) GetText() string {
	if x != nil && x.Text != nil {
		return *x.Text
	}
	return ""
}

func (x *TranslatedString_Translation) GetLanguage() string {
	if x != nil && x.Language != nil {
		return *x.Language
	}
	return ""
}

var File_gtfs_realtime_proto protoreflect.FileDescriptor

const file_gtfs_realtime_proto_rawDesc = "" +
	"\n" +
	"\x13gtfs-realtime.proto\x12\x10transit_realtime\"y\n" +
	"\vFeedMessage\x124\n" +
	"\x06header\x18\x01 \x02(\v2\x1c.transit_realtime.FeedHeaderR\x06header\x124\n" +
	"\x06entity\x18\x02 \x03(\v2\x1c.transit_realtime.FeedEntityR\x06entity\"\xf7\x01\n" +
	"\n" +
	"FeedHeader\x122\n" +
	"\x15gtfs_realtime_version\x18\x01 \x02(\tR\x13gtfsRealtimeVersion\x12a\n" +
	"\x0eincrementality\x18\x02 \x01(\x0e2+.transit_realtime.FeedHeader.Incrementality:\fFULL_DATASETR\x0eincrementality\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x04R\ttimestamp\"4\n" +
	"\x0eIncrementality\x12\x10\n" +
	"\fFULL_DATASET\x10\x00\x12\x10\n" +
	"\fDIFFERENTIAL\x10\x01\"\xed\x01\n" +
	"\n" +
	"FeedEntity\x12\x0e\n" +
	"\x02id\x18\x01 \x02(\tR\x02id\x12$\n" +
	"\n" +
	"is_deleted\x18\x02 \x01(\b:\x05falseR\tisDeleted\x12=\n" +
	"\vtrip_update\x18\x03 \x01(\v2\x1c.transit_realtime.TripUpdateR\n" +
	"tripUpdate\x12;\n" +
	"\avehicle\x18\x04 \x01(\v2!.transit_realtime.VehiclePositionR\avehicle\x12-\n" +
	"\x05alert\x18\x05 \x01(\v2\x17.transit_realtime.AlertR\x05alert\"\x8e\x06\n" +
	"\n" +
	"TripUpdate\x124\n" +
	"\x04trip\x18\x01 \x02(\v2 .transit_realtime.TripDescriptorR\x04trip\x12=\n" +
	"\avehicle\x18\x03 \x01(\v2#.transit_realtime.VehicleDescriptorR\avehicle\x12U\n" +
	"\x10stop_time_update\x18\x02 \x03(\v2+.transit_realtime.TripUpdate.StopTimeUpdateR\x0estopTimeUpdate\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x04R\ttimestamp\x12\x14\n" +
	"\x05delay\x18\x05 \x01(\x05R\x05delay\x1a[\n" +
	"\rStopTimeEvent\x12\x14\n" +
	"\x05delay\x18\x01 \x01(\x05R\x05delay\x12\x12\n" +
	"\x04time\x18\x02 \x01(\x03R\x04time\x12 \n" +
	"\vuncertainty\x18\x03 \x01(\x05R\vuncertainty\x1a\xa2\x03\n" +
	"\x0eStopTimeUpdate\x12#\n" +
	"\rstop_sequence\x18\x01 \x01(\rR\fstopSequence\x12\x17\n" +
	"\astop_id\x18\x04 \x01(\tR\x06stopId\x12D\n" +
	"\aarrival\x18\x02 \x01(\v2*.transit_realtime.TripUpdate.StopTimeEventR\aarrival\x12H\n" +
	"\tdeparture\x18\x03 \x01(\v2*.transit_realtime.TripUpdate.StopTimeEventR\tdeparture\x12\x80\x01\n" +
	"\x15schedule_relationship\x18\x05 \x01(\x0e2@.transit_realtime.TripUpdate.StopTimeUpdate.ScheduleRelationship:\tSCHEDULEDR\x14scheduleRelationship\"?\n" +
	"\x14ScheduleRelationship\x12\r\n" +
	"\tSCHEDULED\x10\x00\x12\v\n" +
	"\aSKIPPED\x10\x01\x12\v\n" +
	"\aNO_DATA\x10\x02\"\xca\a\n" +
	"\x0fVehiclePosition\x124\n" +
	"\x04trip\x18\x01 \x01(\v2 .transit_realtime.TripDescriptorR\x04trip\x12=\n" +
	"\avehicle\x18\b \x01(\v2#.transit_realtime.VehicleDescriptorR\avehicle\x126\n" +
	"\bposition\x18\x02 \x01(\v2\x1a.transit_realtime.PositionR\bposition\x122\n" +
	"\x15current_stop_sequence\x18\x03 \x01(\rR\x13currentStopSequence\x12\x17\n" +
	"\astop_id\x18\a \x01(\tR\x06stopId\x12i\n" +
	"\x0ecurrent_status\x18\x04 \x01(\x0e23.transit_realtime.VehiclePosition.VehicleStopStatus:\rIN_TRANSIT_TOR\rcurrentStatus\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x04R\ttimestamp\x12\\\n" +
	"\x10congestion_level\x18\x06 \x01(\x0e21.transit_realtime.VehiclePosition.CongestionLevelR\x0fcongestionLevel\x12\\\n" +
	"\x10occupancy_status\x18\t \x01(\x0e21.transit_realtime.VehiclePosition.OccupancyStatusR\x0foccupancyStatus\"G\n" +
	"\x11VehicleStopStatus\x12\x0f\n" +
	"\vINCOMING_AT\x10\x00\x12\x0e\n" +
	"\n" +
	"STOPPED_AT\x10\x01\x12\x11\n" +
	"\rIN_TRANSIT_TO\x10\x02\"}\n" +
	"\x0fCongestionLevel\x12\x1c\n" +
	"\x18UNKNOWN_CONGESTION_LEVEL\x10\x00\x12\x14\n" +
	"\x10RUNNING_SMOOTHLY\x10\x01\x12\x0f\n" +
	"\vSTOP_AND_GO\x10\x02\x12\x0e\n" +
	"\n" +
	"CONGESTION\x10\x03\x12\x15\n" +
	"\x11SEVERE_CONGESTION\x10\x04\"\xaf\x01\n" +
	"\x0fOccupancyStatus\x12\t\n" +
	"\x05EMPTY\x10\x00\x12\x18\n" +
	"\x14MANY_SEATS_AVAILABLE\x10\x01\x12\x17\n" +
	"\x13FEW_SEATS_AVAILABLE\x10\x02\x12\x16\n" +
	"\x12STANDING_ROOM_ONLY\x10\x03\x12\x1e\n" +
	"\x1aCRUSHED_STANDING_ROOM_ONLY\x10\x04\x12\b\n" +
	"\x04FULL\x10\x05\x12\x1c\n" +
	"\x18NOT_ACCEPTING_PASSENGERS\x10\x06\"\xfd\x06\n" +
	"\x05Alert\x12@\n" +
	"\ractive_period\x18\x01 \x03(\v2\x1b.transit_realtime.TimeRangeR\factivePeriod\x12I\n" +
	"\x0finformed_entity\x18\x05 \x03(\v2 .transit_realtime.EntitySelectorR\x0einformedEntity\x12B\n" +
	"\x05cause\x18\x06 \x01(\x0e2\x1d.transit_realtime.Alert.Cause:\rUNKNOWN_CAUSER\x05cause\x12F\n" +
	"\x06effect\x18\a \x01(\x0e2\x1e.transit_realtime.Alert.Effect:\x0eUNKNOWN_EFFECTR\x06effect\x124\n" +
	"\x03url\x18\b \x01(\v2\".transit_realtime.TranslatedStringR\x03url\x12C\n" +
	"\vheader_text\x18\n" +
	" \x01(\v2\".transit_realtime.TranslatedStringR\n" +
	"headerText\x12M\n" +
	"\x10description_text\x18\v \x01(\v2\".transit_realtime.TranslatedStringR\x0fdescriptionText\"\xd8\x01\n" +
	"\x05Cause\x12\x11\n" +
	"\rUNKNOWN_CAUSE\x10\x01\x12\x0f\n" +
	"\vOTHER_CAUSE\x10\x02\x12\x15\n" +
	"\x11TECHNICAL_PROBLEM\x10\x03\x12\n" +
	"\n" +
	"\x06STRIKE\x10\x04\x12\x11\n" +
	"\rDEMONSTRATION\x10\x05\x12\f\n" +
	"\bACCIDENT\x10\x06\x12\v\n" +
	"\aHOLIDAY\x10\a\x12\v\n" +
	"\aWEATHER\x10\b\x12\x0f\n" +
	"\vMAINTENANCE\x10\t\x12\x10\n" +
	"\fCONSTRUCTION\x10\n" +
	"\x12\x13\n" +
	"\x0fPOLICE_ACTIVITY\x10\v\x12\x15\n" +
	"\x11MEDICAL_EMERGENCY\x10\f\"\xb5\x01\n" +
	"\x06Effect\x12\x0e\n" +
	"\n" +
	"NO_SERVICE\x10\x01\x12\x13\n" +
	"\x0fREDUCED_SERVICE\x10\x02\x12\x16\n" +
	"\x12SIGNIFICANT_DELAYS\x10\x03\x12\n" +
	"\n" +
	"\x06DETOUR\x10\x04\x12\x16\n" +
	"\x12ADDITIONAL_SERVICE\x10\x05\x12\x14\n" +
	"\x10MODIFIED_SERVICE\x10\x06\x12\x10\n" +
	"\fOTHER_EFFECT\x10\a\x12\x12\n" +
	"\x0eUNKNOWN_EFFECT\x10\b\x12\x0e\n" +
	"\n" +
	"STOP_MOVED\x10\t\"3\n" +
	"\tTimeRange\x12\x14\n" +
	"\x05start\x18\x01 \x01(\x04R\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\x04R\x03end\"\x90\x01\n" +
	"\bPosition\x12\x1a\n" +
	"\blatitude\x18\x01 \x02(\x02R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x02(\x02R\tlongitude\x12\x18\n" +
	"\abearing\x18\x03 \x01(\x02R\abearing\x12\x1a\n" +
	"\bodometer\x18\x04 \x01(\x01R\bodometer\x12\x14\n" +
	"\x05speed\x18\x05 \x01(\x02R\x05speed\"\xe2\x02\n" +
	"\x0eTripDescriptor\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\x12\x19\n" +
	"\broute_id\x18\x05 \x01(\tR\arouteId\x12!\n" +
	"\fdirection_id\x18\x06 \x01(\rR\vdirectionId\x12\x1d\n" +
	"\n" +
	"start_time\x18\x02 \x01(\tR\tstartTime\x12\x1d\n" +
	"\n" +
	"start_date\x18\x03 \x01(\tR\tstartDate\x12j\n" +
	"\x15schedule_relationship\x18\x04 \x01(\x0e25.transit_realtime.TripDescriptor.ScheduleRelationshipR\x14scheduleRelationship\"O\n" +
	"\x14ScheduleRelationship\x12\r\n" +
	"\tSCHEDULED\x10\x00\x12\t\n" +
	"\x05ADDED\x10\x01\x12\x0f\n" +
	"\vUNSCHEDULED\x10\x02\x12\f\n" +
	"\bCANCELED\x10\x03\"^\n" +
	"\x11VehicleDescriptor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12#\n" +
	"\rlicense_plate\x18\x03 \x01(\tR\flicensePlate\"\xb6\x01\n" +
	"\x0eEntitySelector\x12\x1b\n" +
	"\tagency_id\x18\x01 \x01(\tR\bagencyId\x12\x19\n" +
	"\broute_id\x18\x02 \x01(\tR\arouteId\x12\x1d\n" +
	"\n" +
	"route_type\x18\x03 \x01(\x05R\trouteType\x124\n" +
	"\x04trip\x18\x04 \x01(\v2 .transit_realtime.TripDescriptorR\x04trip\x12\x17\n" +
	"\astop_id\x18\x05 \x01(\tR\x06stopId\"\xa3\x01\n" +
	"\x10TranslatedString\x12P\n" +
	"\vtranslation\x18\x01 \x03(\v2..transit_realtime.TranslatedString.TranslationR\vtranslation\x1a=\n" +
	"\vTranslation\x12\x12\n" +
	"\x04text\x18\x01 \x02(\tR\x04text\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguageB3Z1github.com/samirrijal/bilbopass/internal/gtfsrt"

var (
	file_gtfs_realtime_proto_rawDescOnce sync.Once
	file_gtfs_realtime_proto_rawDescData []byte
)

func file_gtfs_realtime_proto_rawDescGZIP() []byte {
	file_gtfs_realtime_proto_rawDescOnce.Do(func() {
		file_gtfs_realtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gtfs_realtime_proto_rawDesc), len(file_gtfs_realtime_proto_rawDesc)))
	})
	return file_gtfs_realtime_proto_rawDescData
}

var file_gtfs_realtime_proto_enumTypes = make([]protoimpl.EnumInfo, 8)
var file_gtfs_realtime_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_gtfs_realtime_proto_goTypes = []any{
	(FeedHeader_Incrementality)(0),                      // 0: transit_realtime.FeedHeader.Incrementality
	(TripUpdate_StopTimeUpdate_ScheduleRelationship)(0), // 1: transit_realtime.TripUpdate.StopTimeUpdate.ScheduleRelationship
	(VehiclePosition_VehicleStopStatus)(0),              // 2: transit_realtime.VehiclePosition.VehicleStopStatus
	(VehiclePosition_CongestionLevel)(0),                // 3: transit_realtime.VehiclePosition.CongestionLevel
	(VehiclePosition_OccupancyStatus)(0),                // 4: transit_realtime.VehiclePosition.OccupancyStatus
	(Alert_Cause)(0),                                    // 5: transit_realtime.Alert.Cause
	(Alert_Effect)(0),                                   // 6: transit_realtime.Alert.Effect
	(TripDescriptor_ScheduleRelationship)(0),            // 7: transit_realtime.TripDescriptor.ScheduleRelationship
	(*FeedMessage)(nil),                                 // 8: transit_realtime.FeedMessage
	(*FeedHeader)(nil),                                  // 9: transit_realtime.FeedHeader
	(*FeedEntity)(nil),                                  // 10: transit_realtime.FeedEntity
	(*TripUpdate)(nil),                                  // 11: transit_realtime.TripUpdate
	(*VehiclePosition)(nil),                             // 12: transit_realtime.VehiclePosition
	(*Alert)(nil),                                       // 13: transit_realtime.Alert
	(*TimeRange)(nil),                                   // 14: transit_realtime.TimeRange
	(*Position)(nil),                                    // 15: transit_realtime.Position
	(*TripDescriptor)(nil),                              // 16: transit_realtime.TripDescriptor
	(*VehicleDescriptor)(nil),                           // 17: transit_realtime.VehicleDescriptor
	(*EntitySelector)(nil),                              // 18: transit_realtime.EntitySelector
	(*TranslatedString)(nil),                            // 19: transit_realtime.TranslatedString
	(*TripUpdate_StopTimeEvent)(nil),                    // 20: transit_realtime.TripUpdate.StopTimeEvent
	(*TripUpdate_StopTimeUpdate)(nil),                   // 21: transit_realtime.TripUpdate.StopTimeUpdate
	(*TranslatedString_Translation)(nil),                // 22: transit_realtime.TranslatedString.Translation
}
var file_gtfs_realtime_proto_depIdxs = []int32{
	9,  // 0: transit_realtime.FeedMessage.header:type_name -> transit_realtime.FeedHeader
	10, // 1: transit_realtime.FeedMessage.entity:type_name -> transit_realtime.FeedEntity
	0,  // 2: transit_realtime.FeedHeader.incrementality:type_name -> transit_realtime.FeedHeader.Incrementality
	11, // 3: transit_realtime.FeedEntity.trip_update:type_name -> transit_realtime.TripUpdate
	12, // 4: transit_realtime.FeedEntity.vehicle:type_name -> transit_realtime.VehiclePosition
	13, // 5: transit_realtime.FeedEntity.alert:type_name -> transit_realtime.Alert
	16, // 6: transit_realtime.TripUpdate.trip:type_name -> transit_realtime.TripDescriptor
	17, // 7: transit_realtime.TripUpdate.vehicle:type_name -> transit_realtime.VehicleDescriptor
	21, // 8: transit_realtime.TripUpdate.stop_time_update:type_name -> transit_realtime.TripUpdate.StopTimeUpdate
	16, // 9: transit_realtime.VehiclePosition.trip:type_name -> transit_realtime.TripDescriptor
	17, // 10: transit_realtime.VehiclePosition.vehicle:type_name -> transit_realtime.VehicleDescriptor
	15, // 11: transit_realtime.VehiclePosition.position:type_name -> transit_realtime.Position
	2,  // 12: transit_realtime.VehiclePosition.current_status:type_name -> transit_realtime.VehiclePosition.VehicleStopStatus
	3,  // 13: transit_realtime.VehiclePosition.congestion_level:type_name -> transit_realtime.VehiclePosition.CongestionLevel
	4,  // 14: transit_realtime.VehiclePosition.occupancy_status:type_name -> transit_realtime.VehiclePosition.OccupancyStatus
	14, // 15: transit_realtime.Alert.active_period:type_name -> transit_realtime.TimeRange
	18, // 16: transit_realtime.Alert.informed_entity:type_name -> transit_realtime.EntitySelector
	5,  // 17: transit_realtime.Alert.cause:type_name -> transit_realtime.Alert.Cause
	6,  // 18: transit_realtime.Alert.effect:type_name -> transit_realtime.Alert.Effect
	19, // 19: transit_realtime.Alert.url:type_name -> transit_realtime.TranslatedString
	19, // 20: transit_realtime.Alert.header_text:type_name -> transit_realtime.TranslatedString
	19, // 21: transit_realtime.Alert.description_text:type_name -> transit_realtime.TranslatedString
	7,  // 22: transit_realtime.TripDescriptor.schedule_relationship:type_name -> transit_realtime.TripDescriptor.ScheduleRelationship
	16, // 23: transit_realtime.EntitySelector.trip:type_name -> transit_realtime.TripDescriptor
	22, // 24: transit_realtime.TranslatedString.translation:type_name -> transit_realtime.TranslatedString.Translation
	20, // 25: transit_realtime.TripUpdate.StopTimeUpdate.arrival:type_name -> transit_realtime.TripUpdate.StopTimeEvent
	20, // 26: transit_realtime.TripUpdate.StopTimeUpdate.departure:type_name -> transit_realtime.TripUpdate.StopTimeEvent
	1,  // 27: transit_realtime.TripUpdate.StopTimeUpdate.schedule_relationship:type_name -> transit_realtime.TripUpdate.StopTimeUpdate.ScheduleRelationship
	28, // [28:28] is the sub-list for method output_type
	28, // [28:28] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_gtfs_realtime_proto_init() }
func file_gtfs_realtime_proto_init() {
	if File_gtfs_realtime_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gtfs_realtime_proto_rawDesc), len(file_gtfs_realtime_proto_rawDesc)),
			NumEnums:      8,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gtfs_realtime_proto_goTypes,
		DependencyIndexes: file_gtfs_realtime_proto_depIdxs,
		EnumInfos:         file_gtfs_realtime_proto_enumTypes,
		MessageInfos:      file_gtfs_realtime_proto_msgTypes,
	}.Build()
	File_gtfs_realtime_proto = out.File
	file_gtfs_realtime_proto_goTypes = nil
	file_gtfs_realtime_proto_depIdxs = nil
}
